language: php

php:
  - 5.6
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - nightly

before_script:
  - composer install -n --dev --prefer-source

script:
  - vendor/phpspec/phpspec/bin/phpspec run -n

